### ISSUE TITLE
Submission 9712924 to Date Test is invalid but got scored

### ISSUE THREAD

**Issue by tschaffter** [nlpsandbox/support#7]
I submitted the Spark NLP tool to the Date Annotation Test queue. The admin table shows that the `status` of the submission is INVALID. The error message returned in the log is included below. It looks like the error is returned by the data node when the controller pushes the prediction to the data node.

Later I received an email `Submission to 'NLP sandbox - Date Annotator - Test' scored!` with the scores.

@thomasyu888 What is the version of the data node deployed on Sage site? I'm assuming that the error happened on Sage data site. From the source code of the data node, `dateFormat` is not required but I think that it was in the past.

```
STDERR: 2021-08-02T03:37:21.686843157Z 	Created Annotation Store
STDERR: 2021-08-02T03:37:21.686848481Z 	Traceback (most recent call last):
STDERR: 2021-08-02T03:37:21.686853740Z 	  File "/usr/local/bin/nlp-cli", line 8, in <module>
STDERR: 2021-08-02T03:37:21.686859568Z 	    sys.exit(main())
STDERR: 2021-08-02T03:37:21.686864380Z 	  File "/usr/local/lib/python3.8/site-packages/nlpsandboxclient/cli/__main__.py", line 19, in main
STDERR: 2021-08-02T03:37:21.686869559Z 	    cli()
STDERR: 2021-08-02T03:37:21.686874684Z 	  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 1137, in __call__
STDERR: 2021-08-02T03:37:21.686880045Z 	    return self.main(*args, **kwargs)
STDERR: 2021-08-02T03:37:21.686884831Z 	  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 1062, in main
STDERR: 2021-08-02T03:37:21.686890368Z 	    rv = self.invoke(ctx)
STDERR: 2021-08-02T03:37:21.686895144Z 	  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 1668, in invoke
STDERR: 2021-08-02T03:37:21.686919732Z 	    return _process_result(sub_ctx.command.invoke(sub_ctx))
STDERR: 2021-08-02T03:37:21.686925699Z 	  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 1668, in invoke
STDERR: 2021-08-02T03:37:21.686931027Z 	    return _process_result(sub_ctx.command.invoke(sub_ctx))
STDERR: 2021-08-02T03:37:21.686935751Z 	  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 1404, in invoke
STDERR: 2021-08-02T03:37:21.686940756Z 	    return ctx.invoke(self.callback, **ctx.params)
STDERR: 2021-08-02T03:37:21.686946000Z 	  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 763, in invoke
STDERR: 2021-08-02T03:37:21.686951160Z 	    return __callback(*args, **kwargs)
STDERR: 2021-08-02T03:37:21.686956038Z 	  File "/usr/local/lib/python3.8/site-packages/nlpsandboxclient/cli/datanode_cli.py", line 50, in store_annotations
STDERR: 2021-08-02T03:37:21.686961696Z 	    client.store_annotations(
STDERR: 2021-08-02T03:37:21.686968480Z 	  File "/usr/local/lib/python3.8/site-packages/nlpsandboxclient/client.py", line 645, in store_annotations
STDERR: 2021-08-02T03:37:21.686973879Z 	    _store_annotation(
STDERR: 2021-08-02T03:37:21.686995985Z 	  File "/usr/local/lib/python3.8/site-packages/nlpsandboxclient/client.py", line 205, in _store_annotation
STDERR: 2021-08-02T03:37:21.687001254Z 	    return annotation_obj.get()
STDERR: 2021-08-02T03:37:21.687005771Z 	  File "/usr/local/lib/python3.8/multiprocessing/pool.py", line 771, in get
STDERR: 2021-08-02T03:37:21.687010266Z 	    raise self._value
STDERR: 2021-08-02T03:37:21.687013995Z 	  File "/usr/local/lib/python3.8/multiprocessing/pool.py", line 125, in worker
STDERR: 2021-08-02T03:37:21.687017951Z 	    result = (True, func(*args, **kwds))
STDERR: 2021-08-02T03:37:21.687021878Z 	  File "/usr/local/lib/python3.8/site-packages/nlpsandbox/api_client.py", line 203, in __call_api
STDERR: 2021-08-02T03:37:21.687026228Z 	    raise e
STDERR: 2021-08-02T03:37:21.687030470Z 	  File "/usr/local/lib/python3.8/site-packages/nlpsandbox/api_client.py", line 196, in __call_api
STDERR: 2021-08-02T03:37:21.687040291Z 	    response_data = self.request(
STDERR: 2021-08-02T03:37:21.687044714Z 	  File "/usr/local/lib/python3.8/site-packages/nlpsandbox/api_client.py", line 455, in request
STDERR: 2021-08-02T03:37:21.687048904Z 	    return self.rest_client.POST(url,
STDERR: 2021-08-02T03:37:21.687052975Z 	  File "/usr/local/lib/python3.8/site-packages/nlpsandbox/rest.py", line 267, in POST
STDERR: 2021-08-02T03:37:21.687077812Z 	    return self.request("POST", url,
STDERR: 2021-08-02T03:37:21.687082999Z 	  File "/usr/local/lib/python3.8/site-packages/nlpsandbox/rest.py", line 224, in request
STDERR: 2021-08-02T03:37:21.687087251Z 	    raise ServiceException(http_resp=r)
STDERR: 2021-08-02T03:37:21.687091378Z 	nlpsandbox.exceptions.ServiceException: (500)
STDERR: 2021-08-02T03:37:21.687095413Z 	Reason: INTERNAL SERVER ERROR
STDERR: 2021-08-02T03:37:21.687099063Z 	HTTP response headers: HTTPHeaderDict({'Content-Type': 'application/json', 'Content-Length': '278'})
STDERR: 2021-08-02T03:37:21.687103291Z 	HTTP response body: {
STDERR: 2021-08-02T03:37:21.687107457Z 	  "detail": "ValidationError (Annotation:None) (dateFormat.Field is required 1.dateFormat.Field is required 2.dateFormat.Field is required 3.dateFormat.Field is required 4.dateFormat.Field is required: ['textDateAnnotations'])",
STDERR: 2021-08-02T03:37:21.687112813Z 	  "status": 500,
STDERR: 2021-08-02T03:37:21.687116898Z 	  "title": "Internal error"
STDERR: 2021-08-02T03:37:21.687121105Z 	}
```

**Comment by tschaffter** [comment]
Tagging @gkowalski because I think that you encountered this issue in the past.

**Comment by gkowalski** [comment]
I remember an issue where conners job failed with an error because the data node contained empty notes. I've removed all of them from our data-node now so that can't be the issue.

**Comment by gkowalski** [comment]
There was a mismatch in the library ( sandbox cli )  I was using to load data to the data-node that caused similar errors. Had to upgrade my python package to fix that one

**Comment by tschaffter** [comment]
The data node has been patched and updated at all data sites.
