### ISSUE TITLE
404 Client Error: Not Found ("No such container

### ISSUE THREAD

**Issue by tschaffter** [nlpsandbox/support#9]
https://www.synapse.org/#!Synapse:syn26021818

```
STDERR: 2021-08-02T15:08:45.228761600Z 	root
STDERR: 2021-08-02T15:08:45.228766301Z 	checking for containers
STDERR: 2021-08-02T15:08:45.228771010Z 	Traceback (most recent call last):
STDERR: 2021-08-02T15:08:45.228777260Z 	  File "/usr/local/lib/python3.6/site-packages/docker/api/client.py", line 220, in _raise_for_status
STDERR: 2021-08-02T15:08:45.228782268Z 	    response.raise_for_status()
STDERR: 2021-08-02T15:08:45.228787115Z 	  File "/usr/local/lib/python3.6/site-packages/requests/models.py", line 943, in raise_for_status
STDERR: 2021-08-02T15:08:45.228791966Z 	    raise HTTPError(http_error_msg, response=self)
STDERR: 2021-08-02T15:08:45.228796769Z 	requests.exceptions.HTTPError: 404 Client Error: Not Found for url: http+docker://localunixsocket/v1.30/containers/b8844f3cb498995f9f025bd5674f0b04cb690be7ce8a546b494823dae483827a/json
STDERR: 2021-08-02T15:08:45.228801910Z
STDERR: 2021-08-02T15:08:45.228806445Z 	During handling of the above exception, another exception occurred:
STDERR: 2021-08-02T15:08:45.228811139Z
STDERR: 2021-08-02T15:08:45.228815650Z 	Traceback (most recent call last):
STDERR: 2021-08-02T15:08:45.228820378Z 	  File "/var/lib/docker/volumes/workflow_orchestrator_shared/_data/40a57526-02f8-4f44-9b8e-41ebfc255ca0/node-07e54b13-c1a0-4433-873d-39488df48e7e-16349ee66b573b0d6cff3dbc6912349f/tmpwrt6mmg0/2b0ce6d1-8e3b-46d5-8a76-1d41395aadf0/tq6nrmsqh/tmp-outwcqdvzpp/start_service.py", line 71, in <module>
STDERR: 2021-08-02T15:08:45.228826344Z 	    main(args)
STDERR: 2021-08-02T15:08:45.228830997Z 	  File "/var/lib/docker/volumes/workflow_orchestrator_shared/_data/40a57526-02f8-4f44-9b8e-41ebfc255ca0/node-07e54b13-c1a0-4433-873d-39488df48e7e-16349ee66b573b0d6cff3dbc6912349f/tmpwrt6mmg0/2b0ce6d1-8e3b-46d5-8a76-1d41395aadf0/tq6nrmsqh/tmp-outwcqdvzpp/start_service.py", line 20, in main
STDERR: 2021-08-02T15:08:45.228836844Z 	    for cont in client.containers.list(all=True):
STDERR: 2021-08-02T15:08:45.228841546Z 	  File "/usr/local/lib/python3.6/site-packages/docker/models/containers.py", line 825, in list
STDERR: 2021-08-02T15:08:45.228846546Z 	    return [self.get(r['Id']) for r in resp]
STDERR: 2021-08-02T15:08:45.228851011Z 	  File "/usr/local/lib/python3.6/site-packages/docker/models/containers.py", line 825, in <listcomp>
STDERR: 2021-08-02T15:08:45.228856108Z 	    return [self.get(r['Id']) for r in resp]
STDERR: 2021-08-02T15:08:45.228860749Z 	  File "/usr/local/lib/python3.6/site-packages/docker/models/containers.py", line 778, in get
STDERR: 2021-08-02T15:08:45.228865608Z 	    resp = self.client.api.inspect_container(container_id)
STDERR: 2021-08-02T15:08:45.228870308Z 	  File "/usr/local/lib/python3.6/site-packages/docker/utils/decorators.py", line 19, in wrapped
STDERR: 2021-08-02T15:08:45.228875254Z 	    return f(self, resource_id, *args, **kwargs)
STDERR: 2021-08-02T15:08:45.228880008Z 	  File "/usr/local/lib/python3.6/site-packages/docker/api/container.py", line 756, in inspect_container
STDERR: 2021-08-02T15:08:45.228888923Z 	    self._get(self._url("/containers/{0}/json", container)), True
STDERR: 2021-08-02T15:08:45.228893915Z 	  File "/usr/local/lib/python3.6/site-packages/docker/api/client.py", line 226, in _result
STDERR: 2021-08-02T15:08:45.228898977Z 	    self._raise_for_status(response)
STDERR: 2021-08-02T15:08:45.228904061Z 	  File "/usr/local/lib/python3.6/site-packages/docker/api/client.py", line 222, in _raise_for_status
STDERR: 2021-08-02T15:08:45.228908808Z 	    raise create_api_error_from_http_exception(e)
STDERR: 2021-08-02T15:08:45.228913431Z 	  File "/usr/local/lib/python3.6/site-packages/docker/errors.py", line 31, in create_api_error_from_http_exception
STDERR: 2021-08-02T15:08:45.228918466Z 	    raise cls(e, response=response, explanation=explanation)
STDERR: 2021-08-02T15:08:45.228923034Z 	docker.errors.NotFound: 404 Client Error: Not Found ("No such container: b8844f3cb498995f9f025bd5674f0b04cb690be7ce8a546b494823dae483827a")
STDERR: 2021-08-02T15:08:45.228928068Z 	[job start_service.cwl] Max memory used: 39MiB
STDERR: 2021-08-02T15:08:45.228932644Z 	INFO:cwltool:[job start_service.cwl] Max memory used: 39MiB
STDERR: 2021-08-02T15:08:45.228937041Z 	[job start_service.cwl] completed permanentFail
STDERR: 2021-08-02T15:08:45.228941506Z 	WARNING:cwltool:[job start_service.cwl] completed permanentFail
STDERR: 2021-08-02T15:08:45.228946139Z 	Traceback (most recent call last):
STDERR: 2021-08-02T15:08:45.228950766Z 	  File "/usr/local/lib/python3.6/site-packages/toil/worker.py", line 366, in workerScript
STDERR: 2021-08-02T15:08:45.228955681Z 	    job._runner(jobGraph=jobGraph, jobStore=jobStore, fileStore=fileStore, defer=defer)
STDERR: 2021-08-02T15:08:45.228960502Z 	  File "/usr/local/lib/python3.6/site-packages/toil/job.py", line 1392, in _runner
STDERR: 2021-08-02T15:08:45.228965357Z 	    returnValues = self._run(jobGraph, fileStore)
STDERR: 2021-08-02T15:08:45.228969904Z 	  File "/usr/local/lib/python3.6/site-packages/toil/job.py", line 1329, in _run
STDERR: 2021-08-02T15:08:45.228974756Z 	    return self.run(fileStore)
STDERR: 2021-08-02T15:08:45.228979358Z 	  File "/usr/local/lib/python3.6/site-packages/toil/cwl/cwltoil.py", line 937, in run
STDERR: 2021-08-02T15:08:45.228984245Z 	    raise cwltool.errors.WorkflowException(status)
STDERR: 2021-08-02T15:08:45.228988800Z 	cwltool.errors.WorkflowException: permanentFail
STDERR: 2021-08-02T15:08:45.228993347Z 	ERROR:toil.worker:Exiting the worker because of a failed job on host ccf2b83dbf9d
```

**Comment by thomasyu888** [comment]
Fixed.
